# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/33bb47a0-9046-4028-9b32-59621da281bc";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/367D-29C0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bd359d61-0907-47d7-8f0f-c23f6e374217"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
